const { Router } =require('express');
const controladorCategoria = require('../controladores/controladorCategoria');
const router = Router();
router.get('/', controladorCategoria.inicio);
router.get('/listar', controladorCategoria.listarcategoria);
router.get('/listarActivas', controladorCategoria.listarcategoriaActivo);
router.post('/guardar', controladorCategoria.guardar);
router.put('/modificar', controladorCategoria.modificar);
router.put('/eliminar', controladorCategoria.eliminar);
module.exports = router;